(cl:defpackage your_package-srv
  (:use )
  (:export
   "CIRCLE"
   "<CIRCLE-REQUEST>"
   "CIRCLE-REQUEST"
   "<CIRCLE-RESPONSE>"
   "CIRCLE-RESPONSE"
   "RECTANGLE"
   "<RECTANGLE-REQUEST>"
   "RECTANGLE-REQUEST"
   "<RECTANGLE-RESPONSE>"
   "RECTANGLE-RESPONSE"
   "SQUARE"
   "<SQUARE-REQUEST>"
   "SQUARE-REQUEST"
   "<SQUARE-RESPONSE>"
   "SQUARE-RESPONSE"
   "TRIANGLE"
   "<TRIANGLE-REQUEST>"
   "TRIANGLE-REQUEST"
   "<TRIANGLE-RESPONSE>"
   "TRIANGLE-RESPONSE"
  ))

