// Generated by gencpp from file your_package/find_Area.msg
// DO NOT EDIT!


#ifndef YOUR_PACKAGE_MESSAGE_FIND_AREA_H
#define YOUR_PACKAGE_MESSAGE_FIND_AREA_H

#include <ros/service_traits.h>


#include <your_package/find_AreaRequest.h>
#include <your_package/find_AreaResponse.h>


namespace your_package
{

struct find_Area
{

typedef find_AreaRequest Request;
typedef find_AreaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct find_Area
} // namespace your_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::your_package::find_Area > {
  static const char* value()
  {
    return "bf0fa91b106c4c70b086c80840d691a8";
  }

  static const char* value(const ::your_package::find_Area&) { return value(); }
};

template<>
struct DataType< ::your_package::find_Area > {
  static const char* value()
  {
    return "your_package/find_Area";
  }

  static const char* value(const ::your_package::find_Area&) { return value(); }
};


// service_traits::MD5Sum< ::your_package::find_AreaRequest> should match
// service_traits::MD5Sum< ::your_package::find_Area >
template<>
struct MD5Sum< ::your_package::find_AreaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::find_Area >::value();
  }
  static const char* value(const ::your_package::find_AreaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::find_AreaRequest> should match
// service_traits::DataType< ::your_package::find_Area >
template<>
struct DataType< ::your_package::find_AreaRequest>
{
  static const char* value()
  {
    return DataType< ::your_package::find_Area >::value();
  }
  static const char* value(const ::your_package::find_AreaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::your_package::find_AreaResponse> should match
// service_traits::MD5Sum< ::your_package::find_Area >
template<>
struct MD5Sum< ::your_package::find_AreaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::find_Area >::value();
  }
  static const char* value(const ::your_package::find_AreaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::find_AreaResponse> should match
// service_traits::DataType< ::your_package::find_Area >
template<>
struct DataType< ::your_package::find_AreaResponse>
{
  static const char* value()
  {
    return DataType< ::your_package::find_Area >::value();
  }
  static const char* value(const ::your_package::find_AreaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOUR_PACKAGE_MESSAGE_FIND_AREA_H
