// Generated by gencpp from file your_package/Rectangle.msg
// DO NOT EDIT!


#ifndef YOUR_PACKAGE_MESSAGE_RECTANGLE_H
#define YOUR_PACKAGE_MESSAGE_RECTANGLE_H

#include <ros/service_traits.h>


#include <your_package/RectangleRequest.h>
#include <your_package/RectangleResponse.h>


namespace your_package
{

struct Rectangle
{

typedef RectangleRequest Request;
typedef RectangleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Rectangle
} // namespace your_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::your_package::Rectangle > {
  static const char* value()
  {
    return "bf0fa91b106c4c70b086c80840d691a8";
  }

  static const char* value(const ::your_package::Rectangle&) { return value(); }
};

template<>
struct DataType< ::your_package::Rectangle > {
  static const char* value()
  {
    return "your_package/Rectangle";
  }

  static const char* value(const ::your_package::Rectangle&) { return value(); }
};


// service_traits::MD5Sum< ::your_package::RectangleRequest> should match
// service_traits::MD5Sum< ::your_package::Rectangle >
template<>
struct MD5Sum< ::your_package::RectangleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::Rectangle >::value();
  }
  static const char* value(const ::your_package::RectangleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::RectangleRequest> should match
// service_traits::DataType< ::your_package::Rectangle >
template<>
struct DataType< ::your_package::RectangleRequest>
{
  static const char* value()
  {
    return DataType< ::your_package::Rectangle >::value();
  }
  static const char* value(const ::your_package::RectangleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::your_package::RectangleResponse> should match
// service_traits::MD5Sum< ::your_package::Rectangle >
template<>
struct MD5Sum< ::your_package::RectangleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::Rectangle >::value();
  }
  static const char* value(const ::your_package::RectangleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::RectangleResponse> should match
// service_traits::DataType< ::your_package::Rectangle >
template<>
struct DataType< ::your_package::RectangleResponse>
{
  static const char* value()
  {
    return DataType< ::your_package::Rectangle >::value();
  }
  static const char* value(const ::your_package::RectangleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOUR_PACKAGE_MESSAGE_RECTANGLE_H
