// Generated by gencpp from file your_package/Square.msg
// DO NOT EDIT!


#ifndef YOUR_PACKAGE_MESSAGE_SQUARE_H
#define YOUR_PACKAGE_MESSAGE_SQUARE_H

#include <ros/service_traits.h>


#include <your_package/SquareRequest.h>
#include <your_package/SquareResponse.h>


namespace your_package
{

struct Square
{

typedef SquareRequest Request;
typedef SquareResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Square
} // namespace your_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::your_package::Square > {
  static const char* value()
  {
    return "5679ee031be5856b91b9f28dfed8edff";
  }

  static const char* value(const ::your_package::Square&) { return value(); }
};

template<>
struct DataType< ::your_package::Square > {
  static const char* value()
  {
    return "your_package/Square";
  }

  static const char* value(const ::your_package::Square&) { return value(); }
};


// service_traits::MD5Sum< ::your_package::SquareRequest> should match
// service_traits::MD5Sum< ::your_package::Square >
template<>
struct MD5Sum< ::your_package::SquareRequest>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::Square >::value();
  }
  static const char* value(const ::your_package::SquareRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::SquareRequest> should match
// service_traits::DataType< ::your_package::Square >
template<>
struct DataType< ::your_package::SquareRequest>
{
  static const char* value()
  {
    return DataType< ::your_package::Square >::value();
  }
  static const char* value(const ::your_package::SquareRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::your_package::SquareResponse> should match
// service_traits::MD5Sum< ::your_package::Square >
template<>
struct MD5Sum< ::your_package::SquareResponse>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::Square >::value();
  }
  static const char* value(const ::your_package::SquareResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::SquareResponse> should match
// service_traits::DataType< ::your_package::Square >
template<>
struct DataType< ::your_package::SquareResponse>
{
  static const char* value()
  {
    return DataType< ::your_package::Square >::value();
  }
  static const char* value(const ::your_package::SquareResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOUR_PACKAGE_MESSAGE_SQUARE_H
