// Generated by gencpp from file your_package/SquareResponse.msg
// DO NOT EDIT!


#ifndef YOUR_PACKAGE_MESSAGE_SQUARERESPONSE_H
#define YOUR_PACKAGE_MESSAGE_SQUARERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace your_package
{
template <class ContainerAllocator>
struct SquareResponse_
{
  typedef SquareResponse_<ContainerAllocator> Type;

  SquareResponse_()
    : result(0.0)  {
    }
  SquareResponse_(const ContainerAllocator& _alloc)
    : result(0.0)  {
  (void)_alloc;
    }



   typedef float _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::your_package::SquareResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::your_package::SquareResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SquareResponse_

typedef ::your_package::SquareResponse_<std::allocator<void> > SquareResponse;

typedef boost::shared_ptr< ::your_package::SquareResponse > SquareResponsePtr;
typedef boost::shared_ptr< ::your_package::SquareResponse const> SquareResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::your_package::SquareResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::your_package::SquareResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::your_package::SquareResponse_<ContainerAllocator1> & lhs, const ::your_package::SquareResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::your_package::SquareResponse_<ContainerAllocator1> & lhs, const ::your_package::SquareResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace your_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::your_package::SquareResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::your_package::SquareResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::your_package::SquareResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::your_package::SquareResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::your_package::SquareResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::your_package::SquareResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::your_package::SquareResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db954e5de3aba73b237d07575e5cac28";
  }

  static const char* value(const ::your_package::SquareResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb954e5de3aba73bULL;
  static const uint64_t static_value2 = 0x237d07575e5cac28ULL;
};

template<class ContainerAllocator>
struct DataType< ::your_package::SquareResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "your_package/SquareResponse";
  }

  static const char* value(const ::your_package::SquareResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::your_package::SquareResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 result\n"
"\n"
;
  }

  static const char* value(const ::your_package::SquareResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::your_package::SquareResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SquareResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::your_package::SquareResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::your_package::SquareResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<float>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOUR_PACKAGE_MESSAGE_SQUARERESPONSE_H
